config/routes.rb
Spree::Core::Engine.add_routes do
  namespace :admin do
    resource :avatax_settings, only: %i[edit update]
    resource :avatax_ping, only: :create

    resources :users do
      member do
        get :avalara_information
        put :avalara_information
      end
    end

    resources :avalara_entity_use_codes, except: :show
  end
end

app/views/spree/admin/users/avalara_information.html.erb
<% content_for :page_title do %>
  <%= link_to @user.email, spree.edit_admin_user_url(@user) %> /
  <%= Spree.t('avalara_entity_use_codes') %>
<% end %>

<%#= render partial: 'spree/admin/users/sidebar', locals: { current: :avalara_informtion } %>

<fieldset data-hook="admin_user_edit_general_settings" class="alpha twelve columns">
  <div data-hook="admin_user_edit_form_header">
    <%= render partial: 'spree/admin/shared/error_messages', locals: { target: @user } %>
  </div>

  <div data-hook="admin_user_edit_form">
    <%= form_for [:admin, @user], method: :put do |f| %>
      <div class="form-group">
        <%= label_tag :avatax_entity_use_code_id, Spree.t(:avalara_entity_use_code) %><br />
        <%= f.select(:avatax_entity_use_code_id, @use_codes, { include_blank: true }, class: 'form-control'  ) %>
      </div>

      <div class="form-group">
        <%= f.label :exemption_number, Spree.t(:exemption_number) %>
        <%= f.text_field :exemption_number, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :vat_id, Spree.t(:vat_identification_number) %>
        <%= f.text_field :vat_id, class: 'form-control' %>
      </div>

      <div class="form-group">
        <% if can?(:update, @user) %>
          <div data-hook="admin_user_edit_form_button">
            <%= render partial: 'spree/admin/shared/edit_resource_links', locals: { collection_url: admin_users_url } %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</fieldset>