config/routes.rb
Spree::Core::Engine.add_routes do
  namespace :admin do
    resource :avatax_settings, only: %i[edit update]
    resource :avatax_ping, only: :create

    resources :users do
      member do
        get :avalara_information
        put :avalara_information
      end
    end

    resources :avalara_entity_use_codes, except: :show
  end
end

app/controllers/spree/admin/avatax_settings_controller.rb
module Spree
  module Admin
    class AvataxSettingsController < Spree::Admin::BaseController
      def edit
        @ship_from_address = SpreeAvataxOfficial::Config.ship_from_address
        @country = if @ship_from_address[:country].blank?
                     current_store.default_country
                   else
                     Spree::Country.find_by(iso3: @ship_from_address[:country])
                   end
        @states = @country.try(:states)
      end

      def update
        if params[:endpoint].present? && params[:endpoint] !~ URI::DEFAULT_PARSER.make_regexp
          flash[:error] = Spree.t('spree_avatax_official.wrong_endpoint_url')
        else
          SpreeAvataxOfficial::Settings::UpdateService.call(params: params)
          flash[:success] = Spree.t('spree_avatax_official.settings_updated')
        end

        redirect_to edit_admin_avatax_settings_path
      end
    end
  end
end

app/views/spree/admin/avatax_settings/edit.html.erb
<h1><%= Spree.t('spree_avatax_official.settings') %></h1>

<%= form_tag(admin_avatax_settings_path, method: :put, id: :avatax_settings_form) do %>

  <div class="yui-g">
    <div class="yui-u first">
      <fieldset>
        <legend><%= Spree.t('spree_avatax_official.enabled') %></legend>
        <div class="checkbox">
          <label>
            <%= hidden_field_tag('enabled', false) %>
            <%= check_box_tag('enabled', true, SpreeAvataxOfficial::Config.enabled) %>
            <%= Spree.t('spree_avatax_official.enabled') %>
          </label>
        </div>
      </fieldset>

      <fieldset>
        <legend><%= Spree.t('spree_avatax_official.avatax_credentials') %></legend>
        <p>
          <label><%= Spree.t('spree_avatax_official.company_code') %></label><br />
          <%= text_field_tag('company_code', SpreeAvataxOfficial::Config.company_code, size: 46, maxlength: 256, class: 'form-control') %>
        </p>

        <p>
          <label><%= Spree.t('spree_avatax_official.account_number') %></label><br />
          <%= text_field_tag('account_number', SpreeAvataxOfficial::Config.account_number, size: 46, maxlength: 256, class: 'form-control') %>
        </p>
        <p>
          <label><%= Spree.t('spree_avatax_official.license_key') %></label><br />
          <%= text_field_tag('license_key', SpreeAvataxOfficial::Config.license_key, size: 46, maxlength: 256, class: 'form-control') %>
        </p>
      </fieldset>

      <fieldset>
        <legend><%= Spree.t('spree_avatax_official.endpoint_urls') %></legend>
        <p>
          <label><%= Spree.t('spree_avatax_official.endpoint') %></label><br />
          <%= text_field_tag('endpoint', SpreeAvataxOfficial::Config.endpoint, size: 46, maxlength: 256, class: 'form-control') %>
        </p>
      </fieldset>

      <fieldset>
        <legend><%= Spree.t('spree_avatax_official.commit_transaction_enabled') %></legend>
        <div class="checkbox">
          <label>
            <%= hidden_field_tag('commit_transaction_enabled', false) %>
            <%= check_box_tag('commit_transaction_enabled', true, SpreeAvataxOfficial::Config.commit_transaction_enabled) %>
            <%= Spree.t('spree_avatax_official.commit_transaction_enabled') %>
          </label>
        </div>
      </fieldset>

      <fieldset>
        <legend><%= Spree.t('spree_avatax_official.address_validation') %></legend>
        <div class="checkbox">
          <label>
            <%= hidden_field_tag('address_validation_enabled', false) %>
            <%= check_box_tag('address_validation_enabled', true, SpreeAvataxOfficial::Config.address_validation_enabled) %>
            <%= Spree.t('spree_avatax_official.enable_address_validation') %>
          </label>
        </p>
      </fieldset>

      <fieldset>
        <legend><%= Spree.t('spree_avatax_official.ship_from_address') %></legend>
        <p>
          <label><%= Spree.t('address1') %></label><br />
          <%= text_field_tag('ship_from[line1]', @ship_from_address[:line1], size: 46, maxlength: 256, class: 'form-control') %>
        </p>
        <p>
          <label><%= Spree.t('address2') %></label><br />
          <%= text_field_tag('ship_from[line2]', @ship_from_address[:line2], size: 46, maxlength: 256, class: 'form-control') %>
        </p>
        <p>
          <label><%= Spree.t('city') %></label><br />
          <%= text_field_tag('ship_from[city]', @ship_from_address[:city], size: 46, maxlength: 256, class: 'form-control') %>
        </p>
        <p>
          <label><%= Spree.t('country') %></label><br />
          <%= select_tag('ship_from[country]', options_from_collection_for_select(Spree::Country.all, 'iso3', 'name', selected: @country.try(:iso3)), class: 'select2') %>
        </p>
        <% if @states.present? && @states.any? %>
          <p>
            <label><%= Spree.t('state') %></label><br />
            <%= select_tag('ship_from[region]', options_from_collection_for_select(@states, 'abbr', 'name', selected: @ship_from_address[:region]), class: 'select2') %>
          </p>
        <% end %>
        <p>
          <label><%= Spree.t('postalcode') %></label><br />
          <%= text_field_tag('ship_from[postal_code]', @ship_from_address[:postalCode], size: 46, maxlength: 25, class: 'form-control') %>
        </p>
      </fieldset>
    </div>
  </div>

  <p class="form-buttons"><%= button Spree.t('spree_avatax_official.save_preferences') %></p>
  <p class="form-buttons"><%=link_to Spree.t('spree_avatax_official.ping_avatax'), :admin_avatax_ping, method: :post, class: 'btn btn-primary' %></p>
<% end %>