config/routes.rb
Spree::Core::Engine.add_routes do
  namespace :admin do
    resource :avatax_settings, only: %i[edit update]
    resource :avatax_ping, only: :create

    resources :users do
      member do
        get :avalara_information
        put :avalara_information
      end
    end

    resources :avalara_entity_use_codes, except: :show
  end
end

app/controllers/spree/admin/avalara_entity_use_codes_controller.rb
module Spree
  module Admin
    class AvalaraEntityUseCodesController < Spree::Admin::BaseController
      before_action :load_use_code, only: %i[edit update destroy]

      def index
        @use_codes = SpreeAvataxOfficial::EntityUseCode.all.order(code: :asc)
        respond_with(@use_codes)
      end

      def new
        @use_code = SpreeAvataxOfficial::EntityUseCode.new
      end

      def edit; end

      def update
        if @use_code.update(entity_use_codes_params)
          redirect_to admin_avalara_entity_use_codes_path, success: Spree.t('spree_avatax_official.entity_use_code_updated')
        else
          redirect_to edit_admin_avalara_entity_use_code_path(@use_code), error: @use_code.errors.full_messages.to_sentence
        end
      end

      def create
        @use_code = SpreeAvataxOfficial::EntityUseCode.new(entity_use_codes_params)
        if @use_code.save
          redirect_to admin_avalara_entity_use_codes_path, success: Spree.t('spree_avatax_official.entity_use_code_created')
        else
          redirect_to new_admin_avalara_entity_use_code_path, error: @use_code.errors.full_messages.to_sentence
        end
      end

      def destroy
        if @use_code.destroy
          flash[:success] = Spree.t('spree_avatax_official.entity_use_code_removed')
        else
          flash[:error] = @use_code.errors.full_messages.to_sentence
        end

        respond_with(@use_code) do |format|
          format.html { redirect_to admin_avalara_entity_use_codes_path }
          format.js   { render_js_for_destroy }
        end
      end

      private

      def load_use_code
        @use_code ||= SpreeAvataxOfficial::EntityUseCode.find(params[:id])
      rescue ActiveRecord::RecordNotFound => e
        flash[:error] = e.message
        redirect_to admin_avalara_entity_use_codes_path
      end

      def entity_use_codes_params
        params.require(:entity_use_code).permit(:code, :name, :description)
      end
    end
  end
end

app/views/spree/admin/avalara_entity_use_codes/_form.html.erb
<div>
  <div class="form-group">
    <%= f.field_container :code do %>
      <%= f.label :code %>
      <%= f.text_field :code, class: 'form-control' %>
    <% end %>
  </div>
  <div class="form-group">
    <%= f.field_container :name do %>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
    <% end %>
  </div>
  <div class="form-group">
    <%= f.field_container :description do %>
      <%= f.label :description %>
      <%= f.text_area :description, class: 'form-control' %>
    <% end %>
  </div>
</div>

app/views/spree/admin/avalara_entity_use_codes/edit.html.erb
<% content_for :page_title do %>
  <%= Spree.t('avalara_entity_use_codes') %>
<% end %>

<%= render 'spree/admin/shared/error_messages', target: @use_code %>

<%= form_for @use_code, url: admin_avalara_entity_use_code_path(@use_code), method: :put do |f| %>
  <fieldset>
    <%= render partial: 'form', locals: { f: f } %>
    <%= render partial: 'spree/admin/shared/edit_resource_links', locals: { collection_url: admin_avalara_entity_use_codes_path }  %>
  </fieldset>
<% end %>

app/views/spree/admin/avalara_entity_use_codes/index.html.erb
<% content_for :page_title do %>
  <%= Spree.t('spree_avatax_official.avalara_entity_use_code_settings') %>
<% end %>

<% content_for :page_actions do %>
  <%= button_link_to Spree.t('spree_avatax_official.avalara entity_use_code'),
                     new_admin_avalara_entity_use_code_url,
                     class: 'btn-success',
                     icon: 'add',
                     id: 'admin_new_avalara_entity_use_code_link' %>
<% end %>

<table class="table" id="listing_sale_events" data-hook>
  <thead>
  <tr data-hook="admin_sale_events_index_headers">
    <th><%= Spree.t(:code) %></th>
    <th><%= Spree.t(:name) %></th>
    <th><%= Spree.t(:description) %></th>
    <th data-hook="admin_sale_events_index_header_actions"></th>
  </tr>
  </thead>
  <tbody>
  <% @use_codes.each do |use_code| %>
    <tr id="<%= dom_id use_code %>" data-hook="admin_sale_events_index_rows">
      <td><%= use_code.code %></td>
      <td><%= use_code.name %></td>
      <td><%= use_code.description %></td>
      <td data-hook="admin_avalara_entity_use_codes_index_row_actions">
        <%= link_to_edit(use_code, url: edit_admin_avalara_entity_use_code_path(use_code)) %>
        <%= link_to_delete(use_code,  { url: admin_avalara_entity_use_code_path(use_code) }) %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/spree/admin/avalara_entity_use_codes/new.html.erb
<% content_for :page_title do %>
  <%= Spree.t('avalara_entity_use_codes') %>
<% end %>

<%= render 'spree/admin/shared/error_messages', target: @use_code %>

<%= form_for @use_code, url: admin_avalara_entity_use_codes_path, html: { multipart: true } do |f| %>
  <fieldset>
    <%= render partial: 'form', locals: { f: f } %>
    <%= render partial: 'spree/admin/shared/new_resource_links', locals: { collection_url: admin_avalara_entity_use_codes_path } %>
  </fieldset>
<% end %>